#!/usr/bin/env node
// Builds the dashboard: fetch GitHub data → render dark/light SVGs → write README.
//   node scripts/build.mjs            fetch fresh data (needs GITHUB_TOKEN or `gh auth login`)
//   node scripts/build.mjs --offline  re-render from data/snapshot.json (no network)
import { readFileSync, writeFileSync, mkdirSync, readdirSync, rmSync } from 'node:fs';
import { fetchData, derive } from './lib/data.mjs';
import { THEMES, esc } from './lib/svg.mjs';
import * as P from './lib/panels.mjs';

const root = new URL('../', import.meta.url);
const path = p => new URL(p, root);
const cfg = JSON.parse(readFileSync(path('profile.config.json'), 'utf8'));
const offline = process.argv.includes('--offline');

const data = offline
  ? JSON.parse(readFileSync(path('data/snapshot.json'), 'utf8'))
  : await fetchData(cfg);
if (!offline) {
  mkdirSync(path('data'), { recursive: true });
  writeFileSync(path('data/snapshot.json'), JSON.stringify(data, null, 1) + '\n');
}
const m = derive(data);

// "auto" follows each viewer's GitHub theme; "dark" or "light" shows that design to everyone.
const mode = cfg.theme ?? 'auto';
const themes = mode === 'auto' ? Object.values(THEMES) : [THEMES[mode]];

mkdirSync(path('assets'), { recursive: true });
const alts = {}, written = new Set();
const out = (name, render) => {
  for (const t of themes) {
    const svg = render(t), file = `${name}-${t.name}.svg`;
    writeFileSync(path(`assets/${file}`), svg);
    written.add(file);
    alts[name] ??= svg.match(/<desc id="d">([^<]*)<\/desc>/)[1];
  }
};

const slug = f => f.symbol.toLowerCase();
const langIndex = lang => { const i = m.langs.findIndex(l => l.name === lang); return i >= 0 && i < 5 ? i : 5; };

out('header', t => P.header(t, cfg, data, m));
out('overview', t => P.overview(t, cfg, data, m));
out('allocation', t => P.allocation(t, cfg, data, m));
for (const f of cfg.featured) out(`card-${slug(f)}`, t => P.card(t, f, data.repos[f.repo], langIndex(data.repos[f.repo].language)));
out('stack', t => P.stack(t, cfg));
cfg.contacts.forEach((c, i) => out(`key-${i + 1}`, t => P.key(t, c)));
out('footer', t => P.footer(t, cfg, data));
// drop SVGs from removed panels or a theme no longer in use
for (const f of readdirSync(path('assets'))) if (f.endsWith('.svg') && !written.has(f)) rmSync(path(`assets/${f}`));

// ---------------------------------------------------------------- README
const pic = (name, width = '100%') => mode === 'auto'
  ? `<picture><source media="(prefers-color-scheme: dark)" srcset="assets/${name}-dark.svg"><img alt="${alts[name]}" src="assets/${name}-light.svg" width="${width}"></picture>`
  : `<img alt="${alts[name]}" src="assets/${name}-${mode}.svg" width="${width}">`;
const link = (url, inner) => `<a href="${esc(url)}">${inner}</a>`;
const repoUrl = f => f.url ?? `https://github.com/${f.repo}`;

const cardRows = [];
for (let i = 0; i < cfg.featured.length; i += 2) {
  cardRows.push(`<p align="center">\n${cfg.featured.slice(i, i + 2).map(f => link(repoUrl(f), pic(`card-${slug(f)}`, '49%'))).join('\n')}\n</p>`);
}

const readme = `<!-- Generated by scripts/build.mjs from profile.config.json. Edit those, then run: node scripts/build.mjs -->

<p align="center">${link(`https://github.com/${cfg.login}`, pic('header'))}</p>

<p align="center">${pic('overview')}</p>

<p align="center">${pic('allocation')}</p>

${cardRows.join('\n\n')}

${cfg.more?.length ? `<details>
<summary><b>More positions</b>: ${cfg.more.map(x => x.title).join(', ')}</summary>
<br>

| Project | What it is |
|:--|:--|
${cfg.more.map(x => `| [${x.title}](https://github.com/${x.repo}) | ${x.blurb} |`).join('\n')}

</details>
` : ''}
<p align="center">${pic('stack')}</p>

<p align="center">
${cfg.contacts.map((c, i) => link(c.url, pic(`key-${i + 1}`, '32%'))).join('\n')}
</p>

<p align="center">${pic('footer')}</p>
`;
writeFileSync(path('README.md'), readme);
console.log(`Built ${written.size} SVGs + README.md (${offline ? 'offline' : 'fresh data'}, ${data.year.contributions} contributions/yr).`);
